// Sandbox styles — carried over from the prototype, with its
// palette swapped for the app's theme tokens (see constants.js).
// The app shell styles (safe area, tab bar) are dropped: the
// sandbox sits inside the app's own Screen and tab bar now.

import { StyleSheet } from 'react-native';
import { C } from './constants';
import { STRUCT_FONT } from './fonts';

export const st = StyleSheet.create({






  explainBtn:{ paddingHorizontal:11, justifyContent:"center", borderRadius:11,
               backgroundColor:C.surf, borderWidth:1, borderColor:C.border },
  explainOn:{ backgroundColor:C.green, borderColor:C.green },
  explainTxt:{ fontSize:11, fontWeight:"800", color:C.sub },
  styleBtn:{ paddingHorizontal:9, justifyContent:"center", borderRadius:11,
             backgroundColor:C.surf, borderWidth:1, borderColor:C.border },

  banner:{ marginHorizontal:12, marginBottom:6, padding:11, borderRadius:14,
           backgroundColor:C.surf, borderWidth:1, borderColor:C.border,
           minHeight:64, justifyContent:"center" },
  bannerOk:{ borderColor:C.blue },
  bannerDone:{ backgroundColor:"#F1FBF6", borderColor:C.green },
  taskLabel:{ fontSize:10.5, fontWeight:"800", color:C.sub,
              letterSpacing:0.6, textTransform:"uppercase" },
  taskName:{ fontSize:19, fontWeight:"800", color:C.navy, marginTop:2,
             fontFamily:STRUCT_FONT },
  taskOk:{ fontSize:13.5, color:C.green, fontWeight:"700", marginTop:6 },
  taskNo:{ fontSize:13.5, color:C.navy, marginTop:6, lineHeight:18 },
  taskHint:{ fontSize:12.5, color:C.sub, marginTop:5, lineHeight:17, fontStyle:"italic" },
  taskRow:{ flexDirection:"row", gap:8, marginTop:10 },
  bannerErr:{ backgroundColor:"#FFF6F6", borderColor:"#F5CFCF" },
  bannerHint:{ fontSize:14, color:C.sub, textAlign:"center" },
  bannerName:{ fontSize:20, fontWeight:"800", color:C.navy, fontFamily:STRUCT_FONT },
  reasonBtn:{ alignSelf:"center", marginTop:8, paddingVertical:5, paddingHorizontal:14,
              borderRadius:999, backgroundColor:C.surf2 },
  reasonTxt:{ fontSize:11.5, fontWeight:"700", color:C.blue },
  bannerMeta:{ fontSize:12.5, color:C.sub, marginTop:3 },
  bannerErrCode:{ fontSize:11, fontWeight:"800", color:C.red,
                  letterSpacing:0.6, textTransform:"uppercase" },
  bannerErrMsg:{ fontSize:14, color:C.navy, marginTop:4, lineHeight:19 },

  steps:{ maxHeight:170, marginHorizontal:12, marginBottom:8, borderRadius:12,
          backgroundColor:C.surf, borderWidth:1, borderColor:C.border },
  stepT:{ fontSize:10.5, fontWeight:"800", color:C.blue,
          letterSpacing:0.6, textTransform:"uppercase" },
  stepB:{ fontSize:13.5, color:C.navy, marginTop:2, lineHeight:19 },

  canvasWrap:{ marginHorizontal:12, borderRadius:14, backgroundColor:C.surf,
               borderWidth:1, borderColor:C.border, overflow:"hidden" },
  canvasTools:{ position:"absolute", right:8, top:8, gap:6 },
  canvasToolsL:{ position:"absolute", left:8, top:8, gap:6 },
  toolBtn:{ minWidth:38, minHeight:34, paddingHorizontal:9, borderRadius:9,
            alignItems:"center", justifyContent:"center",
            backgroundColor:"rgba(255,255,255,0.94)",
            borderWidth:1, borderColor:C.border },
  toolBtnOn:{ backgroundColor:C.blue, borderColor:C.blue },
  toolTxt:{ fontSize:17, fontWeight:"800", color:C.blue, lineHeight:20 },
  toolTxtSm:{ fontSize:11, fontWeight:"700", color:C.sub },
  empty:{ position:"absolute", top:0, left:0, right:0, bottom:0,
          alignItems:"center", justifyContent:"center", padding:24 },
  emptyT:{ fontSize:17, fontWeight:"700", color:C.navy, marginBottom:8 },
  emptyB:{ fontSize:13, color:C.sub, textAlign:"center", lineHeight:20 },

  elRow:{ paddingHorizontal:12, paddingVertical:7, gap:7, alignItems:"center" },
  elBtn:{ width:46, height:46, borderRadius:12, alignItems:"center", justifyContent:"center",
          backgroundColor:C.surf, borderWidth:1, borderColor:C.border },
  elWide:{ width:84 },
  elBtnOn:{ backgroundColor:C.blue, borderColor:C.blue },
  elTxt:{ fontSize:16, fontWeight:"800" },
  elTxtSm:{ fontSize:12.5, fontWeight:"700", color:C.sub },

  actions:{ flexDirection:"row", gap:6, paddingHorizontal:12, paddingBottom:10 },
  act:{ flex:1, minHeight:48, borderRadius:12, alignItems:"center", justifyContent:"center",
        backgroundColor:C.surf, borderWidth:1, borderColor:C.border },
  actPrimary:{ flex:1.5, backgroundColor:C.blue, borderColor:C.blue },
  actPrimaryTxt:{ fontSize:14, fontWeight:"800", color:"#fff" },
  actDanger:{ backgroundColor:C.red, borderColor:C.red },
  actOn:{ backgroundColor:C.blue, borderColor:C.blue },
  actTxt:{ fontSize:13, fontWeight:"700", color:C.sub },
  tplRow:{ paddingHorizontal:12, paddingTop:8, gap:6, alignItems:"center" },
  tplBtn:{ minHeight:38, paddingHorizontal:12, borderRadius:10, alignItems:"center",
           justifyContent:"center", backgroundColor:C.surf2, borderWidth:1, borderColor:C.border },
  tplAlt:{ backgroundColor:C.surf },
  tplBtnOn:{ backgroundColor:C.blue, borderColor:C.blue },
  tplIcon:{ width:44, height:40, borderRadius:10, alignItems:"center",
            justifyContent:"center", backgroundColor:C.surf2,
            borderWidth:1, borderColor:C.border },
  tplTxt:{ fontSize:12.5, fontWeight:"700", color:C.blue },
  bondRow:{ flexDirection:"row", gap:6, paddingHorizontal:12, paddingTop:7 },
  bondBtn:{ flex:1, minHeight:44, borderRadius:11, alignItems:"center", justifyContent:"center",
            backgroundColor:C.surf, borderWidth:1, borderColor:C.border },
  bondBtnOn:{ backgroundColor:C.blue, borderColor:C.blue },
  bondGlyph:{ fontSize:17, fontWeight:"800", color:C.navy, lineHeight:20 },
  bondHint:{ fontSize:9.5, fontWeight:"700", color:C.sub, marginTop:1 },
  selfStart:{ alignSelf:"flex-start", flex:0, paddingHorizontal:18, marginBottom:12 },

  input:{ backgroundColor:C.surf, borderWidth:1, borderColor:C.border, borderRadius:12,
          paddingHorizontal:14, paddingVertical:12, fontSize:16, color:C.navy,
          fontFamily:STRUCT_FONT },
  chips:{ flexDirection:"row", flexWrap:"wrap", gap:7, marginTop:10, marginBottom:14 },
  chip:{ backgroundColor:C.surf2, borderRadius:999, paddingHorizontal:11, paddingVertical:8 },
  chipTxt:{ fontSize:12, color:C.blue, fontWeight:"600", fontFamily:STRUCT_FONT },
  card:{ backgroundColor:C.surf, borderRadius:14, padding:16, borderWidth:1,
         borderColor:C.border, alignItems:"center" },
  cardErr:{ backgroundColor:"#FFF6F6", borderColor:"#F5CFCF" },
  cardBad:{ backgroundColor:"#FDECEC", borderColor:C.red, borderWidth:2 },
  cardBadMsg:{ color:"#8C1D1D", fontWeight:"600" },
  badBanner:{ alignSelf:"stretch", backgroundColor:C.red, borderRadius:8,
              paddingVertical:7, paddingHorizontal:12, marginBottom:12 },
  badBannerTxt:{ color:"#fff", fontSize:12.5, fontWeight:"800",
                 textAlign:"center", letterSpacing:0.3 },
  fixBtn:{ marginTop:12, backgroundColor:C.blue, borderRadius:10,
           paddingVertical:10, paddingHorizontal:18 },
  fixTxt:{ color:"#fff", fontSize:13.5, fontWeight:"700" },
  cardName:{ fontSize:19, fontWeight:"800", color:C.navy, marginTop:8,
             textAlign:"center", fontFamily:STRUCT_FONT },
  cardMeta:{ fontSize:12.5, color:C.sub, marginTop:3, fontFamily:STRUCT_FONT },
  cardMetaHint:{ fontSize:11.5, color:C.sub, marginTop:4, fontStyle:"italic" },
  nameRow:{ flexDirection:"row", flexWrap:"wrap", justifyContent:"center",
            alignItems:"flex-end", marginTop:10 },
  namePart:{ borderBottomWidth:2, borderBottomColor:C.border },
  namePartOn:{ color:C.blue, borderBottomColor:C.blue,
               backgroundColor:C.surf2, borderRadius:4 },
  partBox:{ marginTop:9, backgroundColor:C.surf2, borderRadius:9,
            paddingVertical:8, paddingHorizontal:12, alignSelf:"stretch" },
  partTxt:{ fontSize:13, color:C.navy, textAlign:"center", lineHeight:18 },
  cardErrMsg:{ fontSize:14, color:C.navy, marginTop:6, lineHeight:20, textAlign:"center" },
  note:{ fontSize:12, color:C.amber, marginTop:6, textAlign:"center" },
  synBox:{ marginTop:11, alignSelf:"stretch", borderTopWidth:1,
           borderTopColor:C.border, paddingTop:9 },
  synLabel:{ fontSize:10.5, fontWeight:"800", color:C.sub, textAlign:"center",
             letterSpacing:0.5, textTransform:"uppercase" },
  synRow:{ flexDirection:"row", flexWrap:"wrap", justifyContent:"center",
           gap:6, marginTop:7 },
  synChip:{ backgroundColor:C.surf2, borderRadius:999,
            paddingHorizontal:10, paddingVertical:6 },
  synChipTrivial:{ backgroundColor:"#EAF7F0" },
  synTxt:{ fontSize:12, color:C.blue, fontWeight:"600", fontFamily:STRUCT_FONT },
  synTxtTrivial:{ color:C.green },
  noteBox:{ marginTop:10, backgroundColor:"#FFF7E8", borderColor:"#F5DFAF",
            borderWidth:1, borderRadius:9, paddingVertical:8, paddingHorizontal:12,
            alignSelf:"stretch", alignItems:"center" },
  noteBoxFlag:{ backgroundColor:"#FFF1DC", borderColor:C.amber, borderWidth:2 },
  noteFlag:{ fontSize:10.5, fontWeight:"800", color:"#8A5B12",
             letterSpacing:0.6, textTransform:"uppercase", marginBottom:4 },
  noteTxt:{ fontSize:12.5, color:"#8A5B12", textAlign:"center", lineHeight:17 },
  noteTxtFlag:{ fontWeight:"600" },
});

